import * as React from 'react';
import Accordion from '@mui/material/Accordion';
import { useSession, signIn, signOut } from "next-auth/react"
import AccordionSummary from '@mui/material/AccordionSummary';
import AccordionDetails from '@mui/material/AccordionDetails';
import Typography from '@mui/material/Typography';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logo from '../public/img/logo.png';
import tv from '../public/img/tv.png';
import mobile from '../public/img/mobile.jpg';
import device from '../public/img/device.png';
import kids from '../public/img/kids.png';

export default function Home() {
  const { data: session } = useSession()
    const handlesignin = (e) => {
      e.preventDefault()
      signIn()      
    }

    const handlesigout = (e) => {
      e.preventDefault()
      signOut()      
    }
  return (
    <div className={styles.container}>
      <Head>
        
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
          <div className={styles.main}>
          <div className={styles.navbar}>
            <div className={styles.img}>
            <Image width={140} height={44.19} src={logo} alt="logo"/>
            </div>
            <div className={styles.btns}>
              <select>
                <option>English</option>
                <option>Arabic</option>
                <option>Frensh</option>
              </select>
              {session &&  <button onClick={handlesigout}>sign out</button>}
              {!session && <button onClick={handlesignin}>Sign in</button>}
             
              
      
  
            </div>
            
          </div>

          <div className={styles.article}>
            <h1>Unlimited movies, TV <br /> shows, and more.</h1>
            <h2>Watch anywhere. Cancel anytime.</h2>
            <h3>Ready to watch? Enter your email to create or restart your membership.</h3>
            <div className={styles.ard}>
            <input type="text" placeholder="email adresse"/>
            <button>get started  ></button>
            </div>
          </div>
          </div>

          <div className={styles.article1}>
            <div className={styles.infos}>
              <h1>Enjoy on your TV.</h1>
              <h2>Watch on Smart TVs, Playstation, Xbox, <br /> Chromecast, Apple TV, Blu-ray players, and <br /> more.</h2>
            </div>
            <div className={styles.image}>
              <Image src={tv} width={483} height={362} alt="tv"/>
            </div>
          </div>

          <div className={styles.article2}>
            <div className={styles.picture}>
              <Image src={mobile} alt="mobile"/>
            </div>
            <div className={styles.content}>
              <h1>Download your shows <br /> to watch offline.</h1>
              <h2>Save your favorites easily and always have <br /> something to watch.</h2>
            </div>
          </div>

          <div className={styles.article3}>
            <div className={styles.content1}>
              <h1>Watch everywhere.</h1>
              <h2>Stream unlimited movies and TV shows on <br /> your phone, tablet, laptop, and TV without <br /> paying more.</h2>
            </div>
            <div>
              <Image src={device} alt="device"/>
            </div>
          </div>

          <div className={styles.article4}>
            <div>
              <Image src={kids} alt="device"/>
            </div>
            <div className={styles.content1}>
              <h1>Create profiles for kids..</h1>
              <h2>Send kids on adventures with their favorite <br /> characters in a space made just for them— <br />free with your membership..</h2>
            </div>
          </div>
          <div className={styles.article5}>
            <h1>Frequently Asked Questions</h1>
          <Accordion className={styles.accordio}>
        <AccordionSummary className={styles.AccordionSummary}
          expandIcon={<ExpandMoreIcon />}
          aria-controls="panel1a-content"
          id="panel1a-header"
        >
          <Typography>What is Netflix?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography className={styles.typography}>
          Netflix is a streaming service that offers a wide variety of award-winning TV shows, movies, anime, documentaries, and more on thousands of internet-connected devices.

You can watch as much as you want, whenever you want without a single commercial – all for one low monthly price. There's always something new to discover and new TV shows and movies are added every week!
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion className={styles.accordio}>
        <AccordionSummary className={styles.AccordionSummary}
          expandIcon={<ExpandMoreIcon />}
          aria-controls="panel2a-content"
          id="panel2a-header"
        >
          <Typography>How much does Netflix cost?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography className={styles.typography}>
          Watch anywhere, anytime. Sign in with your Netflix account to watch instantly on the web at netflix.com from your personal computer or on any internet-connected device that offers the Netflix app, including smart TVs, smartphones, tablets, streaming media players and game consoles.

You can also download your favorite shows with the iOS, Android, or Windows 10 app. Use downloads to watch while you're on the go and without an internet connection. Take Netflix with you anywhere.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion className={styles.accordio}>
        <AccordionSummary className={styles.AccordionSummary}
          expandIcon={<ExpandMoreIcon />}
          aria-controls="panel2a-content"
          id="panel2a-header"
        >
          <Typography>How do I cancel?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography className={styles.typography}>
          Netflix is flexible. There are no pesky contracts and no commitments. You can easily cancel your account online in two clicks. There are no cancellation fees – start or stop your account anytime.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion className={styles.accordio}>
        <AccordionSummary className={styles.AccordionSummary}
          expandIcon={<ExpandMoreIcon />}
          aria-controls="panel2a-content"
          id="panel2a-header"
        >
          <Typography>What can I watch on Netflix?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography className={styles.typography}>
          Netflix has an extensive library of feature films, documentaries, TV shows, anime, award-winning Netflix originals, and more. Watch as much as you want, anytime you want.
          </Typography>
        </AccordionDetails>
      </Accordion>

      <Accordion className={styles.accordio}>
        <AccordionSummary className={styles.AccordionSummary}
          expandIcon={<ExpandMoreIcon />}
          aria-controls="panel2a-content"
          id="panel2a-header"
        >
          <Typography>Is Netflix good for kids?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography className={styles.typography}>
          The Netflix Kids experience is included in your membership to give parents control while kids enjoy family-friendly TV shows and movies in their own space.
Kids profiles come with PIN-protected parental controls that let you restrict the maturity rating of content kids can watch and block specific titles you don’t want kids to see.
          </Typography>
        </AccordionDetails>
      </Accordion>

      <h3>Ready to watch? Enter your email to create or restart your membership.</h3>
      <div className={styles.type}>
      <input placeholder="enter your email"/>
      <button>get started ></button>
      </div>
          </div>
        </main>

        <footer className={styles.footer}>
          <div >
          <a href='#'>Questions? Contact us.</a>
          <div className={styles.foorent}>
          <ul>
             <li className={styles.li}>FAQ</li>
             <li className={styles.li}>Investor Relations</li>
             <li className={styles.li}>Privacy</li>
             <li className={styles.li}>Speed Test</li>
             <li className={styles.li}> <select>
                            <option>English</option>
                            <option>Arabic</option>
                            <option>Frensh</option>
                            <option>Deutsh</option>
                        </select></li>
                        <li className={styles.li}>Netflix Morocco</li>
           </ul>
           <ul>
             <li className={styles.li} >Help Center</li>
             <li className={styles.li} >Jobs</li>
             <li className={styles.li} >Cookie Preferences</li>
             <li className={styles.li} >Legal Notices</li>
             
           </ul>

           <ul>
             <li className={styles.li} >Account</li>
             <li className={styles.li} >Ways to Watch</li>
             <li className={styles.li} >Corporate Information</li>
             <li className={styles.li} >Only on Netflix</li>
           </ul>

           <ul>
             <li className={styles.li}>Media Center</li>
             <li className={styles.li}>Terms of Use</li>
             <li className={styles.li}>Contact Us</li>
           </ul>
           </div>
          </div>
        </footer>
     
    </div>
  )
}
